portal/urls.py
from django.conf import settings
from django.http import HttpResponse
from django.urls import include, path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view

from . import apis, models, views

# app_name = "portal"  ## in case if there is anohter app, add this prefix
urlpatterns = [
    # path('<int:pk>', ProductDetailView.as_view(), name="product-detail"),
    # path("", TemplateView.as_view(template_name="pages/comingsoon.html"), name="comingsoon"),
    path(
        "webmanifest",
        cache_page(None)(
            TemplateView.as_view(
                template_name="pages/webmanifest.html", content_type="application/json"
            )
        ),
        name="webmanifest",
    ),
    path("about", views.about, name="about"),
    path("logout", views.logout, name="logout"),
    path("status", views.status, name="status"),
    path(
        "robots.txt",
        cache_page(None)(
            lambda *args, **kwargs: HttpResponse(
                "User-agent: *\nDisallow: /", content_type="text/plain"
            )
        ),
    ),
    path("subscriptions/", views.SubscriptionList.as_view(), name="subscriptions"),
    path("users/<int:pk>/profile", views.user_profile, name="user-profile"),
    path(
        "applications/",
        include(
            [
                path(
                    "summary",
                    views.SummaryReportList.as_view(),
                    name="summary-report",
                ),
                path(
                    "<int:application>/evaluation/~create",
                    views.CreateEvaluation.as_view(),
                    name="application-evaluation-create",
                ),
                path(
                    "<int:pk>/evaluation/~edit",
                    views.edit_evaluation,
                    name="application-evaluation",
                ),
                path(
                    "<int:round>/~create",
                    views.ApplicationCreate.as_view(),
                    name="application-create",
                ),
                path(
                    "<int:pk>/~update",
                    views.ApplicationUpdate.as_view(),
                    name="application-update",
                ),
                path("<int:pk>", views.ApplicationDetail.as_view(), name="application"),
                path(
                    "<int:application>/review/~create",
                    views.TestimonialView.as_view(),
                    name="application-review-create",
                ),
                path("draft", views.ApplicationList.as_view(), name="applications-draft"),
                path("submitted", views.ApplicationList.as_view(), name="applications-submitted"),
                path("", views.ApplicationList.as_view(), name="applications"),
                path(
                    "<int:pk>/~export",
                    views.ApplicationExportView.as_view(),
                    name="application-export",
                ),
                path(
                    "<number>/exported-view",
                    views.application_exported_view,
                    name="application-exported-view",
                ),
                path("<number>/summary", views.application_summary, name="application-summary"),
            ]
        ),
    ),
    path(
        "evaluation/",
        include(
            [
                path("<int:pk>", views.EvaluationDetail.as_view(), name="evaluation"),
                path(
                    "<int:pk>/~update", views.UpdateEvaluation.as_view(), name="evaluation-update"
                ),
            ]
        ),
    ),
    path("myprofile/", views.user_profile, name="my-profile"),
    path("account/", views.AccountView.as_view(), name="account"),
    path(
        "identity-verification/",
        include(
            [
                path(
                    "<int:pk>/file",
                    views.IdentityVerificationFileView.as_view(),
                    name="identity-verification-file",
                ),
                path(
                    "<int:pk>",
                    views.IdentityVerificationView.as_view(),
                    name="identity-verification",
                ),
            ]
        ),
    ),
    path("profiles/<int:pk>", views.ProfileDetail.as_view(), name="profile-instance"),
    path(
        "profile/",
        include(
            [
                path("~create", views.ProfileCreate.as_view(), name="profile-create"),
                # path("profiles/<int:pk>/~update", views.ProfileUpdate.as_view(), name="profile-update"),
                path("~update", views.ProfileUpdate.as_view(), name="profile-update"),
                path(
                    "career-stages/",
                    views.ProfileCareerStageFormSetView.as_view(),
                    name="profile-career-stages",
                ),
                path(
                    "external-ids/",
                    views.ProfilePersonIdentifierFormSetView.as_view(),
                    name="profile-external-ids",
                ),
                path(
                    "employments/",
                    views.ProfileEmploymentsFormSetView.as_view(),
                    name="profile-employments",
                ),
                path(
                    "educations/",
                    views.ProfileEducationsFormSetView.as_view(),
                    name="profile-educations",
                ),
                path(
                    "academic-records/",
                    views.ProfileAcademicRecordFormSetView.as_view(),
                    name="profile-academic-records",
                ),
                path(
                    "recognitions/",
                    views.ProfileRecognitionFormSetView.as_view(),
                    name="profile-recognitions",
                ),
                path(
                    "protection-patterns/",
                    views.profile_protection_patterns,
                    name="profile-protection-patterns",
                ),
                path(
                    "disable-protection-patterns/",
                    views.disable_profile_protection_patterns,
                    name="disable-profile-protection-patterns",
                ),
                path(
                    "cvs/",
                    views.ProfileCurriculumVitaeFormSetView.as_view(),
                    name="profile-cvs",
                ),
                path("files/", views.user_files, name="profile-files"),
                path("~check", views.check_profile, name="check-profile"),
                path(
                    "professional/",
                    views.ProfileProfessionalFormSetView.as_view(),
                    name="profile-professional-records",
                ),
                path(
                    "summary/<username>",
                    views.ProfileSummaryView.as_view(),
                    name="profile-summary",
                ),
                path("", views.ProfileDetail.as_view(), name="profile"),
            ]
        ),
    ),
    path("start", views.index, name="start"),
    path("", views.index, name="index"),
    # path("index", views.index, name="index"),
    path("home", views.index, name="home"),
    path("index.html", views.index, name="index.html"),
    path("photo_identity", views.photo_identity, name="photo-identity"),
    # path("test_task/<message>", views.test_task),
    path("onboard/<token>", views.check_profile, name="onboard-with-token"),
    path("onboard", views.check_profile, name="onboard"),
    path("approve/<user_id>", view=views.approve_user, name="approve-user"),
    # path("profile/career-stages", views.profile_career_stages, name="profile-career-stages"),
    # path('', ProductListView.as_view(), name="product-list"),
    # path("subscription/create", views.SubscriptionCreate.as_view(), name="subscription-create"),
    path("subscription/<int:pk>", views.SubscriptionDetail.as_view(), name="subscription-detail"),
    path("ui_kit", TemplateView.as_view(template_name="pages/ui_kit.html"), name="ui_kit"),
    path(
        "autocomplete/",
        include(
            [
                path(
                    "iwi_group/",
                    views.IwiGroupAutocomplete.as_view(model=models.IwiGroup),
                    name="iwi-group-autocomplete",
                ),
                path(
                    "ethnicity/",
                    views.EthnicityAutocomplete.as_view(model=models.Ethnicity),
                    name="ethnicity-autocomplete",
                ),
                path(
                    "org/",
                    views.OrgAutocomplete.as_view(model=models.Organisation, create_field="name"),
                    name="org-autocomplete",
                ),
                path(
                    "fos/",
                    views.FosAutocomplete.as_view(model=models.FieldOfStudy),
                    name="fos-autocomplete",
                ),
                path(
                    "award/",
                    views.AwardAutocomplete.as_view(model=models.Award, create_field="name"),
                    name="award-autocomplete",
                ),
                path(
                    "qualification/",
                    views.QualificationAutocomplete.as_view(
                        model=models.Qualification, create_field="description"
                    ),
                    name="qualification-autocomplete",
                ),
                path(
                    "person-identifier/",
                    views.PersonIdentifierAutocomplete.as_view(
                        model=models.PersonIdentifierType, create_field="description"
                    ),
                    name="person-identifier-autocomplete",
                ),
            ]
        ),
    ),
    path(
        "invitations/",
        include(
            [

portal/users/urls.py
from django.urls import path

from portal.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("~redirect/", view=views.user_redirect_view, name="redirect"),
    path("~update/", view=views.user_update_view, name="update"),
    path("<str:username>/", view=views.user_detail_view, name="detail"),
]

portal/templates/account.html
{% extends 'base.html' %}

{% load static i18n socialaccount django_bootstrap_breadcrumbs %}

{% block sidebar %}{% include 'sidebar.html' with category="account" %}{% endblock sidebar %}
{% block title %}User: {{ user.full_name_with_email }}{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Your Account" "account" %}
{% endblock %}

{% block content %}

  <h1>
    {% if user and user == request.user %}
      {% trans 'Your Account' %}
    {% else %}
      {{ user.full_name_with_email|title }}
    {% endif %}
  </h1>

  <div class="row">

    <div class="col-9">

      <table class="table table-bordered searchable">
        <tbody>
          <tr>
            <th style="width: 32%; min-width: 160px; max-width: 180px;">{% trans 'Primary email address' %}</th>
            <td>{{ user.email }}</td>
          </tr>

          {% if emails %}
            <tr>
              <th>{% trans 'Secondary email addresses' %}</th>
              <td>
                <ul>
                  {% for ea in emails %}
                    <li>
                      {{ ea.email |default_if_none:"" }}
                    </li>
                  {% endfor %}
                </ul>
              </td>
            </tr>
          {% endif %}
          <tr>
            <th>{% trans 'First name' %}</th>
            <td>{{ user.first_name|default_if_none:"" }}</td>
          </tr>
          {% if user.middle_names %}
            <tr>
              <th>{% trans 'Middle name(s)' %}</th>
              <td>{{ user.middle_names_name|default_if_none:"" }}</td>
            </tr>
          {% endif %}
          <tr>
            <th>{% trans 'Last name' %}</th>
            <td>{{ user.last_name|default_if_none:"" }}</td>
          </tr>
          {% if accounts %}
            <tr>
              <th>{% trans 'Linked accounts' %}</th>
              <td>
                <ul>
                  {% for base_account in accounts %}
                    {% with base_account.get_provider_account as account %}
                      <li>
                        <span class="socialaccount_provider {{ base_account.provider }} {{ account.get_brand.id }}">{{account.get_brand.name}}: </span>{{ account }}
                      </li>
                    {% endwith %}
                  {% endfor %}
                </ul>
              </td>
            </tr>
          {% endif %}

        </tbody>
      </table>

      {% if user == request.user %}
        <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">{% trans 'My Info' %}</a>
        <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">{% trans 'E-Mail Addresses' %}</a>
        <a class="btn btn-primary" href="{% url 'socialaccount_connections' %}" role="button">{% trans 'Linked Accounts' %}</a>
      {% endif %}

    </div>
  </div>

{% endblock %}

portal/templates/application-export.html
{% load i18n tags %}
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}
</style>

{% include 'snippets/application-export-header.html' %}

{% with a=application u=user %}
<div style="margin-top:36%;border-color:grey;border-width:2px;border-style:solid;margin-left:10%;margin-right:5%;font-size:15px;padding:25px;border-radius:25px;">
  <table>
      <center>
          <h2>
          {{ a.number }}: {{ a.application_title|default:a.round.title }}
          </h2>
      </center>
      <tr><th>{% trans 'Number' %}</th><td>{{ a.number }}</td></tr>
      <tr><th>{% trans 'Title' %}</th><td>{{ a.application_title|default:a.round.title }}</td></tr>
      <tr><th>{% trans 'Applicant' %}</th><td>{{ a.full_name }}</td></tr>
  </table>
</div>

<div class="mb-2" id="header_content" style="page-break-before: always">
  {% include 'snippets/application-export-header.html' %}
</div>

  <h2>
    {{ a.number }}: {{ a.application_title|default:a.round.title|title }}
  </h2>
  {% include 'snippets/application_detail_table.html' %}
{% endwith %}

{% for object in objects %}
<h2>
  {{ object }}
</h2>
<table class="table table-bordered searchable">
  <tbody>

  {% for field in object|fields %}
    {% with name=field.name %}
      {% if name != 'budget' and name != 'organisation' and name != 'id' and not show_summary and name != 'summary' and name != 'summary_en' and name != 'summary_mi' and exclude is None or name not in exclude %}

        <tr>
          <th style="width: 21%; min-width: 160px; max-width: 180px;">{{ field.verbose_name|title }}</th>
          <td>
            {% if field.name == "file" %}
              {{ object.file.name|basename }}
            {% elif field.name == "converted_file" %}
              {{ object.converted_file.file.name|basename }}
            {% else %}
              {{ object|field_value:field.name }}
            {% endif %}
          </td>
        </tr>

      {% endif %}
    {% endwith %}
  {% endfor %}

  </tbody>
</table>
{% endfor %}

</body>
</html>

portal/templates/form_errors.html
{% for field in form %}
    {% for error in field.errors %}
      {% if error != '' %}
        <div class="alert alert-danger">{{ error|safe }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
      {% endif %}
    {% endfor %}
{% endfor %}

{% for error in form.non_field_errors %}
  <div class="alert alert-danger">{{ error|safe }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
{% endfor %}

portal/templates/nomination.html
{% extends "form.html" %}
{% load i18n django_bootstrap_breadcrumbs %}

{% block sidebar %}{% include 'sidebar.html' with category="nominations" %}{% endblock sidebar %}

{% block content_header %}
  {{ round|title }}
{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Nominations" "nominations" %}
  {% if object.status == "submitted" %}
    {% breadcrumb "Submitted" "nominations-submitted" %}
  {% elif not object or object.status == "draft" or object.status == "new" %}
    {% breadcrumb "Draft" "nominations-draft" %}
  {% endif %}
  {% if object %}
    {% breadcrumb object "nomination-update" pk=object.pk %}
  {% elif round %}
    {% breadcrumb round "nomination-create" round=round.pk %}
  {% endif %}
{% endblock %}

{% block content %}
  {{ block.super }}
  <!-- Privacy Statement Modal -->
  <div class="modal fade" id="confirm-submit" tabindex="-1" role="dialog"
    aria-labelledby="privacy-statement-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="privacy-statement-title">{% trans 'Confirmation' %}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% blocktranslate %}
            All information in this report is true to the best of my knowledge.
            <br />
            <br />
            I acknowledge that I may be contacted to provide further information in relation to this prize application.
          {% endblocktranslate %}
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
            {% trans 'Cancel' %}
          </button>
          <a href="#" id="submit-button" class="btn btn-primary success" data-dismiss="modal">
            {% trans 'Submit' %}
          </a>
        </div>

      </div>
    </div>
  </div>
{% endblock %}

{% block javascript %}
  {{ block.super }}
  {% if object and object.status != "accepted" or not object %}
  <script>
    $(document).ready(function(){
      $('#button-id-submit_button').click(function() {
        if (this.form.checkValidity()) $('#confirm-submit').modal('show');
        else this.form.reportValidity();
      });
      $('#submit-button').click(function(){
        /* when the submit button in the modal is clicked, submit the form */
        var form = document.getElementById('nomination-form');
        if (form.checkValidity()) {
          form.action.value = "submit";
          form.submit();
        }
        else form.reportValidity();
      });
    });
  </script>
  {% endif %}
{% endblock %}

portal/templates/nominations.html
{% extends "table.html" %}

{% load static i18n django_bootstrap_breadcrumbs %}
{% load render_table from django_tables2 %}

{% block breadcrumbs %}
  {% breadcrumb_raw_safe '<i class="fa fa-fw fa-home"></i>' "/" %}
  {% breadcrumb "Nominations" "nominations" %}
  {% if state == "draft" %}
    {% breadcrumb "Draft" "nominations-draft" %}
  {% elif state == "submitted" %}
    {% breadcrumb "Submitted" "nominations-submitted" %}
  {% endif %}
{% endblock %}

{% block sidebar %}{% include 'sidebar.html' with category="nominations" %}{% endblock sidebar %}

portal/templates/panelist.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
  {{ formset.media.css }}
  {{ block.super }}
{% endblock %}

{% load static i18n %}
{% block sidebar %}{% include 'sidebar.html' with categrory="applications" %}{% endblock sidebar %}

{% block content_header %}
  {{ round|title }}
{% endblock %}
{% block content %}
    {% crispy formset helper %}
{% endblock %}

{% block javascript %}
  {{ block.super }}
  {{ formset.media.js }}
{% endblock %}

portal/templates/panellist.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags django_bootstrap_breadcrumbs %}

{% block css %}
  {{ formset.media.css }}
  {{ block.super }}
{% endblock %}

{% load static i18n %}
{% block sidebar %}{% include 'sidebar.html' with category="applications" %}{% endblock sidebar %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Panellists" "panellist-invite" %}
{% endblock %}

{% block content %}
  <!-- Panellist Deletion Modal -->
  <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog"
    aria-labelledby="delete-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
      <div class="modal-content">
        <div class="modal-header modal-header-bg">
          <h1 class="modal-title" id="delete-title">{% trans 'Are you sure?' %}</h1>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="confirm-delete-body">
          {% blocktranslate %}
            Do you wish to delete this panellist and all linked data entries to this panellist?
          {% endblocktranslate %}
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
            {% trans 'Cancel' %}
          </button>
          <a href="#" id="submit-button" class="btn btn-danger" data-dismiss="modal">
            {% trans "Yes, I'm sure" %}
          </a>
          <button type="button" class="btn btn-success" data-dismiss="modal">
            {% trans 'No, take me back' %}
          </button>
        </div>

      </div>
    </div>
  </div>
  <h2 data-toggle="tooltip" title="{% trans 'The panellist of the round' %}">
    {{ round|title }}
  </h2>
  {% crispy formset helper %}
{% endblock %}

{% block javascript %}
  <script>
    var delete_field;
    var formset_form
    function confirm_deletion(el, message) {
      delete_field = el;
      formset_form = delete_field.parents("form").first()[0];
      $("#confirm-delete-body").first()[0].innerHTML = message;
      $('#confirm-delete').modal('show');
      return false;
    }
    $(document).ready(function(){
      $('#submit-button').click(function(){
        delete_field.val("on");
        let form = delete_field.parents("form").first()[0]
        form.action.value = "submit";
        form.submit();
      });
    });
  </script>
  <script src="{% static 'js/project.js' %}"></script>
  {{ block.super }}
  {{ formset.media.js }}
{% endblock %}

portal/templates/rounds.html
{% extends "table.html" %}

{% load static i18n django_bootstrap_breadcrumbs %}
{% load render_table from django_tables2 %}

{% block breadcrumbs %}
  {% breadcrumb_raw_safe '<i class="fa fa-fw fa-home"></i>' "/" %}
  {% breadcrumb "Reviews" "reviews" %}
  {% if state == "draft" %}
    {% breadcrumb "Draft" "reviews-draft" %}
  {% elif state == "submitted" %}
    {% breadcrumb "Submitted" "reviews-submitted" %}
  {% endif %}
  {% if round %}
    {% if state %}
      {% breadcrumb round.title "round-application-list-with-state" round_id=round.pk state=state %}
    {% else %}
      {% breadcrumb round.title "round-application-list" round_id=round.pk %}
    {% endif %}
  {% endif %}
  {% if application %}
    {% if state %}
      {% breadcrumb application "round-application-reviews-list" round_id=round.pk application_id=application.pk %}
    {% else %}
      {% breadcrumb application "round-application-reviews-list-with-state" round_id=round.pk state=state application_id=application.pk %}
    {% endif %}
  {% endif %}
{% endblock %}

{% block sidebar %}{% include 'sidebar.html' with category="reviews" %}{% endblock sidebar %}

{% block content %}
  {% if round %}
    <h2>
      {{ round.title|default:round.scheme.title }}
    </h2>
  {% elif application %}
    <h2>
      {{ application.number }}:
      {{ application.title|default:application.round.title }}
    </h2>
  {% endif %}

  {% if round and is_panellist %}
    <p>
    <a class="btn btn-primary"
       data-toggle="tooltip"
       title="{% trans 'Submit Conflict of Interest Statements in batch for the whole round' %}"
       href="{% url 'round-coi' round=round.pk %}"
       >
       {% trans 'Conflict of Interest Statements' %}
    </a>
    </p>
  {% endif %}

  {% render_table table %}
{% endblock %}

portal/templates/testimonial_detail.html
{% extends 'detail.html' %}

{% load i18n crispy_forms_tags tags django_bootstrap_breadcrumbs %}
{% block sidebar %}{% include 'sidebar.html' with category="testimonials" %}{% endblock sidebar %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Testimonials" "testimonials" %}
  {% if object.state == "draft" or object.state == "new" %}
    {% breadcrumb "Draft" "testimonials-draft" %}
  {% elif object.state == "submitted" %}
    {% breadcrumb "Submitted" "testimonials-submitted" %}
  {% endif %}
  {% breadcrumb object view_name pk=object.pk %}
{% endblock %}

{% block content %}

  {% if start_applying %}
    <a class="btn btn-primary" href="{{ start_applying }}">
      {% trans 'Start Prize Application' %}
    </a>
  {% endif %}

  {% if form %}
    {% block css %}
      {{ form.media.css }}
      {{ block.super }}
    {% endblock %}
    {% crispy form %}
    {% block javascript %}
      {{ block.super }}
      {{ form.media.js }}
    {% endblock %}
  {% endif %}

  {{ block.super }}

{% endblock %}

portal/templates/testimonials.html
{% extends "table.html" %}

{% load static i18n django_bootstrap_breadcrumbs %}
{% load render_table from django_tables2 %}

{% block breadcrumbs %}
  {% breadcrumb_raw_safe '<i class="fa fa-fw fa-home"></i>' "/" %}
  {% breadcrumb "Testimonials" "testimonials" %}
  {% if state == "draft" %}
    {% breadcrumb "Draft" "testimonials-draft" %}
  {% elif state == "submitted" %}
    {% breadcrumb "Submitted" "testimonials-submitted" %}
  {% endif %}
{% endblock %}

{% block sidebar %}{% include 'sidebar.html' with category="testimonials" %}{% endblock sidebar %}

portal/templates/testimony_detail.html
{% extends 'detail.html' %}

{% load i18n crispy_forms_tags tags %}
{% block sidebar %}{% include 'sidebar.html' with category="testimonies" %}{% endblock sidebar %}

{% block content %}

  {% if start_applying %}
    <a class="btn btn-primary" href="{{ start_applying }}">
      {% trans 'Start Applying' %}
    </a>
  {% endif %}

  {% if form %}
    {% block css %}
      {{ form.media.css }}
      {{ block.super }}
    {% endblock %}
    {% crispy form %}
    {% block javascript %}
      {{ block.super }}
      {{ form.media.js }}
    {% endblock %}
  {% endif %}

  {{ block.super }}

{% endblock %}

portal/templates/user_files.html
{% extends 'profile.html' %}
{% load crispy_forms_tags static i18n %}

{% block css %}
  {{ ethics_statement_formset.media.css }}
  {{ identity_verifications_formset.media.css }}
  {{ block.super }}
{% endblock %}


{% block head_title %}{{ object }}{% endblock %}
{% block sidebar %}{% include 'sidebar.html' with category="profile" %}{% endblock sidebar %}

{% block section %}

  <form {{ flat_attrs|safe }} method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ ethics_statement_formset.management_form }}
    {{ identity_verification_formset.management_form }}

    {% if ethics_statement_queryset.count > 0 %}
      {% crispy ethics_statement_formset ethics_statement_formset.helper %}
    {% endif %}

    {% if identity_verification_queryset.count > 0 %}
      {% crispy identity_verification_formset identity_verification_formset.helper %}
    {% endif %}

    <div class="buttonHolder buttonHolder mb-5 float-right">
      <input type="submit" name="save" value="{% trans 'Save' %}" class="btn btn btn-primary" id="save" data-toggle="tooltip" title="{% trans 'Save' %}">
      <a href="{% url 'profile' %}" type="button" role="button" class="btn btn-secondary" id="cancel">{% trans 'Cancel' %}</a>
    </div>

  </form>
{% endblock %}

{% block javascript %}
  {{ block.super }}
  {{ identity_verification_formset.media.js }}
  {{ ethics_statement_formset.media.js }}
  <!-- script>
    /* $('#add_more').click(function() {
    var form_idx = $('#id_form-TOTAL_FORMS').val();
    var el = $('<tr>' + $('#empty_form').html().replace(/__prefix__/g, form_idx) + '</tr>') ;
    setDatePickers(el);
    $('#form_set').append(el);
    $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
    }); */
    /* $(".modelselect2").select2({ */
    /*   width: null // remove calculated with of the select2 span elements */
    /* }); */
    </script -->
  {% endblock %}